site_name: ZJU OS
site_url: https://zju-os.github.io/doc/
site_description: 浙江大学操作系统课程实验指导
site_author: 浙江大学计算机科学与技术学院
copyright: 浙江大学计算机科学与技术学院
repo_url: https://github.com/ZJU-OS/doc
repo_name: ZJU-OS/doc
edit_uri: blob/main/docs/

nav:
  - 首页: index.md
  - 实验文档:
    - intro.md
    - faq.md
    - lab0.md
    - lab1.md
    - lab2.md
    - z1-spike.md
  - RISC-V 规范:
    - 特权级规范: spec/riscv-privileged.html
    - 非特权级规范: spec/riscv-unprivileged.html
    - ELF ABI 规范: spec/riscv-abi.pdf
    - SBI 规范: spec/riscv-sbi.pdf
    - 汇编规范: spec/riscv-asm.pdf
    - 汇编教程: https://riscv-programming.org/
  - 工具文档:
    - QEMU: https://www.qemu.org/docs/master/index.html
    - GDB: https://sourceware.org/gdb/current/onlinedocs/gdb
    - GCC: https://gcc.gnu.org/onlinedocs/
    - as: https://sourceware.org/binutils/docs/as
    - ld: https://sourceware.org/binutils/docs/ld
    - binutils: https://sourceware.org/binutils/docs/binutils
  - 源码仓库:
    - Linux (GitHub): https://github.com/torvalds/linux
    - Linux (Cross Referencer): https://elixir.bootlin.com/
    - OpenSBI: https://github.com/riscv-software-src/opensbi
    - QEMU: https://github.com/qemu/qemu/
  - 助教文档: ta

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    # 代码块操作
    - content.code.copy
    - content.code.select
    - content.code.annotate
    # 底部导航
    - navigation.footer
    # 顶部导航
    #- navigation.tabs
    # 侧边栏按 section 展开
    - navigation.sections
    - navigation.expand
    # 章节首页 index.md
    - navigation.indexes
    # 锚点
    - navigation.tracking
    # 路径
    - navigation.path
    # 回到顶部
    - navigation.top
    - toc.follow
    # 页面编辑
    - content.action.edit
    # 搜索
    - search.suggest
    - search.highlight
    - search.share

markdown_extensions:
  # Admonition
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      # Mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format:
            !!python/name:pymdownx.superfences.fence_code_format # Code Block
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Tab Card
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  # Grid, Image
  - attr_list
  - md_in_html
  # Icon
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg # List
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  # TOC
  - toc:
      permalink: true
      # 中文锚点
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  # MathJax
  - pymdownx.arithmatex:
      generic: true
  # Keys
  - pymdownx.keys
  # Highlight
  - pymdownx.critic
  # 时间轴、甘特图
  - neoteroi.timeline
  - neoteroi.projects


extra_javascript:
  # MathJax
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/polyfill/index.min.js
  - https://cdn.jsdelivr.net/npm/mathjax/es5/tex-mml-chtml.js
  # Table Sort
  - https://cdn.jsdelivr.net/npm/tablesort/dist/tablesort.min.js
  - javascripts/tablesort.js
  # mermaid
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js

extra_css:
  - stylesheets/fonts.css
  - stylesheets/counter.css
  - stylesheets/neoteroi-v1.1.2.css

plugins:
  - glightbox
  - drawio
  - tags
  - search
  - timetoread
  - include_dir_to_nav:
      recurse: false
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
      locale: zh
  # 该插件本地编辑时关闭，CI 时自动开启
  - git-committers:
      enabled: false
      repository: zju-os/doc
      branch: main
